# Generated by Django 5.0.5 on 2024-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_birth_date_alter_profile_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код активации'),
        ),
    ]
