# Generated by Django 5.0.5 on 2024-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='e-mail подтверждён'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='номер телефона подтверждён'),
        ),
    ]
