# Generated by Django 5.0.5 on 2024-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email_confirmed_profile_phone_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Код активации')),
            ],
        ),
    ]
