# Generated by Django 5.0.5 on 2024-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_preregistrationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistrationdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
    ]
