# Generated by Django 5.0.5 on 2024-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_preregistrationdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistrationdata',
            name='time_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправления'),
        ),
    ]
