# Generated by Django 5.0.5 on 2024-05-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courselevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Уровень курса')),
            ],
        ),
    ]
