# Generated by Django 5.0.5 on 2024-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursesubcategory_name_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='preview',
            field=models.ImageField(default=0, upload_to='courses/cat_preview', verbose_name='Превью'),
            preserve_default=False,
        ),
    ]
